<a href="https://colab.research.google.com/github/D3stro9er/neural-networks/blob/main/lab2/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №2

### студента групи Анд-31
### Українець Андрій
### Варіант №11

# Завдання №1
### створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

Tmatrix = tf.random.Generator.from_seed(42)
Tmatrix = Tmatrix.normal(shape=(5, 5))
print("Tensor list:\n",Tmatrix)
print("Shape of tensor: ", Tmatrix.shape)
print("Rank of tensor:", Tmatrix.ndim)
print("Size  of tensor:", tf.size(Tmatrix).numpy())
print("Elements along axis 0 of tensor:",Tmatrix.shape[0])
print("Elements along axis 1 of tensor:",Tmatrix.shape[1])

Tensor list:
 tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193765]
 [-1.8107855   0.09988727 -0.50998646 -0.7535806  -0.5716629 ]
 [ 0.1480774  -0.23362991 -0.3522796   0.40621266 -1.0523509 ]
 [ 1.2054597   1.6874489  -0.44629744 -2.3410842   0.99009085]
 [-0.08763231 -0.635568   -0.6161736  -1.9441465  -0.48293006]], shape=(5, 5), dtype=float32)
Shape of tensor:  (5, 5)
Rank of tensor: 2
Size  of tensor: 25
Elements along axis 0 of tensor: 5
Elements along axis 1 of tensor: 5


# Завдання №2
### продемонструвати основні математичні операції над тензорами.

In [2]:
print("Add value to a tensor:", Tmatrix + 0.3)

Add value to a tensor: tf.Tensor(
[[-0.45658028  0.231453    0.37595028 -0.9573844   0.06806237]
 [-1.5107856   0.39988726 -0.20998645 -0.45358056 -0.2716629 ]
 [ 0.4480774   0.0663701  -0.05227959  0.70621264 -0.75235087]
 [ 1.5054598   1.9874489  -0.14629743 -2.0410843   1.2900908 ]
 [ 0.2123677  -0.335568   -0.3161736  -1.6441464  -0.18293005]], shape=(5, 5), dtype=float32)


In [3]:
print("Multiplication:", Tmatrix * 1.5)

Multiplication: tf.Tensor(
[[-1.1348704  -0.10282053  0.11392538 -1.8860767  -0.34790647]
 [-2.7161784   0.14983091 -0.7649797  -1.1303709  -0.85749435]
 [ 0.2221161  -0.35044485 -0.5284194   0.609319   -1.5785263 ]
 [ 1.8081896   2.5311732  -0.6694462  -3.5116262   1.4851363 ]
 [-0.13144848 -0.95335203 -0.92426044 -2.9162197  -0.7243951 ]], shape=(5, 5), dtype=float32)


In [4]:
print("Subtraction:", Tmatrix - 0.4)

Subtraction: tf.Tensor(
[[-1.1565803  -0.46854702 -0.32404974 -1.6573844  -0.6319376 ]
 [-2.2107856  -0.30011272 -0.9099865  -1.1535805  -0.9716629 ]
 [-0.2519226  -0.6336299  -0.75227964  0.00621265 -1.4523509 ]
 [ 0.80545974  1.2874489  -0.84629744 -2.7410843   0.5900909 ]
 [-0.48763233 -1.035568   -1.0161736  -2.3441465  -0.88293004]], shape=(5, 5), dtype=float32)


In [5]:
Tmatrix_aux = tf.random.Generator.from_seed(12)
Tmatrix_aux = Tmatrix_aux.normal(shape=(5, 3))
print("Auxiliary tensor:", Tmatrix_aux)

Auxiliary tensor: tf.Tensor(
[[-1.0130816   0.2829171   1.2132235 ]
 [ 0.46988973  0.37944326 -0.6664026 ]
 [ 0.6054596   0.19181173  0.8045827 ]
 [ 0.4769051  -0.7812124  -0.996891  ]
 [ 0.33149976 -0.5445254   1.5222508 ]], shape=(5, 3), dtype=float32)


In [6]:
print("multiplicate tensor to a tensor:", tf.matmul(Tmatrix,Tmatrix_aux))

multiplicate tensor to a tensor: tf.Tensor(
[[ 0.10371249  0.8830891   0.08929522]
 [ 1.0237408   0.3277694  -2.7927554 ]
 [-0.62821496  0.14136638 -1.9549872 ]
 [-1.4867892   2.1854856   3.819861  ]
 [-1.670201    1.3976151   1.0244255 ]], shape=(5, 3), dtype=float32)


# Завдання №3
### провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame.

In [7]:
#Update and delete operations are forbidden for constant tensor because we use variable that update our tensor.
Vmatrix = tf.Variable([[1,2,3,4],
                      [1,2,3,4],
                      [2,5,2,6]])
print("Update tensor:")
Vmatrix[0].assign([2,5,2,6])

Update tensor:


<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=int32, numpy=
array([[2, 5, 2, 6],
       [1, 2, 3, 4],
       [2, 5, 2, 6]], dtype=int32)>

In [13]:
data = np.array([])
with open("tensor.txt") as f:
    for line in f:
       data = np.append(data,[float(x) for x in line.split()])
TmatrixF = tf.constant(data, shape = (5,2))
print("Upload from file:",TmatrixF)

Upload from file: tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]
 [9. 0.]], shape=(5, 2), dtype=float64)


In [9]:
resh = np.arange(1, 25)
resh

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [10]:
Tmatrix_resh = tf.constant(resh, shape=(6, 4))
Tmatrix_resh

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [11]:
first_arr = [1, 2, 3, 4, 5, 6, 7, 8]
second_arr = [10, 11, 12, 13, 14, 15, 16 ,17]
df = pd.DataFrame({'fisrt':first_arr,
                  'second':second_arr})
df

fisrt  second
0      1      10
1      2      11
2      3      12
3      4      13
4      5      14
5      6      15
6      7      16
7      8      17

In [12]:
TmatrixD = tf.constant(df)
TmatrixD

<tf.Tensor: shape=(8, 2), dtype=int64, numpy=
array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14],
       [ 6, 15],
       [ 7, 16],
       [ 8, 17]])>

# Висновок
### В ході виконання лабораторної роботи було розглянуто бібліотеку tensorflow. За допомогою цієї бібліотеки ми створювали тензори різного рангу, також розглянули різні види заповнення тензорів. Попрацювали з властивостями та математичними операціями над тензорами. Також провели CRUD операції і зробили інтеграцію з np.array та DataFrame в тензор. Тензор в основному використовують, як ваговы коефіцієнти для навчання нейронних мерж.